// Dimensions are metres, with each asset's origin on the floor at its centre.
export const HOME_ASSETS = [
  { kind: 'block', name: '体块', size: '1 × 1 × 1 m' },
  { kind: 'woodFloor', name: '木地板', size: '1 × 1 m' },
  { kind: 'tileFloor', name: '瓷砖地面', size: '1 × 1 m' },
  { kind: 'dressedBed', name: '双人软床', size: '1.8 × 2.15 m' },
  { kind: 'singleBed', name: '单人床', size: '1 × 2.1 m' },
  { kind: 'sofa', name: '双人沙发', size: '1.85 × 0.85 m' },
  { kind: 'woodTable', name: '木桌', size: '1.4 × 0.8 m' },
  { kind: 'woodChair', name: '餐椅', size: '0.48 × 0.52 m' },
  { kind: 'cabinet', name: '矮柜', size: '1.2 × 0.42 m' },
  { kind: 'bookshelf', name: '书柜', size: '1.2 × 0.35 m' },
  { kind: 'wardrobe', name: '衣柜', size: '1.6 × 0.6 m' },
  { kind: 'window', name: '推拉窗', size: '1 × 1 m' },
  { kind: 'curtain', name: '窗帘', size: '1 × 1 m' },
  { kind: 'doorPanel', name: '门扇', size: '0.85 × 2.1 m' },
  { kind: 'rug', name: '地毯', size: '1 × 1 m' },
  { kind: 'plant', name: '盆栽', size: '0.65 × 1.15 m' },
  { kind: 'tv', name: '电视', size: '1.15 × 0.72 m' },
  { kind: 'lamp', name: '台灯', size: '0.28 × 0.48 m' },
  { kind: 'picture', name: '挂画', size: '0.6 × 0.8 m' },
  { kind: 'counter', name: '橱柜台面', size: '1 × 0.65 m' },
  { kind: 'kitchenSink', name: '厨房水槽', size: '0.55 × 0.42 m' },
  { kind: 'cooktop', name: '双灶', size: '0.6 × 0.4 m' },
  { kind: 'fridge', name: '冰箱', size: '0.72 × 0.7 m' },
  { kind: 'basin', name: '洗手台', size: '0.75 × 0.5 m' },
  { kind: 'toilet', name: '马桶', size: '0.4 × 0.68 m' },
  { kind: 'bathtub', name: '浴缸', size: '1.6 × 0.72 m' },
  { kind: 'shower', name: '淋浴隔断', size: '1.3 × 0.1 m' },
  { kind: 'washer', name: '滚筒洗衣机', size: '0.6 × 0.6 m' },
  { kind: 'railing', name: '阳台栏杆', size: '1 × 1.05 m' },
] as const;
export type HomeAssetKind = (typeof HOME_ASSETS)[number]['kind'];
